on:
  push:
    branches: main
  schedule:
    - cron: '0 1 * * *'

name: Opdater_kursus_metadata

jobs:
  render:
    name: opdaterer_metadata
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev
          sudo apt-get install -y libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev
          sudo apt-get install -y libfontconfig1-dev libfreetype6-dev libfribidi-dev libharfbuzz-dev
      - name: Install packages
        run: |
          Rscript -e 'install.packages("curl")'
          Rscript -e 'install.packages("here")'
          Rscript -e 'install.packages("tidyverse")'
          Rscript -e 'install.packages("httr")'
          Rscript -e 'install.packages("httr2")'
          Rscript -e 'install.packages("readr")'
          Rscript -e 'install.packages("openssl")'
          Rscript -e 'install.packages("zoo")'
      - name: Opdater kursus metadata
        env: 
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET}}
        run: Rscript -e 'source("scripts/opdater_metadata.R")'
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A .
          git commit -m 'Opdateret kursus metadata' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
